<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * ================== COUNTRIES ===================
         */
        $countries = [
            'id' => 1,
            'name' => 'INDONESIA',
            'description' => 'Indonesia',
            'created_by' => 'System',
            'updated_by' => 'System',
        ];

        DB::table('countries')->insert($countries);

        /**
         * ================== PROVINCES ===================
         */

         $provinces = [
             ['id' => 11, 'name' => 'ACEH', 'description' => 'ACEH','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 12, 'name' => 'SUMATERA UTARA', 'description' => 'SUMATERA UTARA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 13, 'name' => 'SUMATERA BARAT', 'description' => 'SUMATERA BARAT','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 14, 'name' => 'RIAU', 'description' => 'RIAU','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 15, 'name' => 'JAMBI', 'description' => 'JAMBI','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 16, 'name' => 'SUMATERA SELATAN', 'description' => 'SUMATERA SELATAN','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 17, 'name' => 'BENGKULU', 'description' => 'BENGKULU','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 18, 'name' => 'LAMPUNG', 'description' => 'LAMPUNG','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 19, 'name' => 'KEPULAUAN BANGKA BELITUNG', 'description' => 'KEPULAUAN BANGKA BELITUNG','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 21, 'name' => 'KEPULAUAN RIAU', 'description' => 'KEPULAUAN RIAU','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 31, 'name' => 'DKI JAKARTA', 'description' => 'DKI JAKARTA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 32, 'name' => 'JAWA BARAT', 'description' => 'JAWA BARAT','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 33, 'name' => 'JAWA TENGAH', 'description' => 'JAWA TENGAH','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 34, 'name' => 'DI YOGYAKARTA', 'description' => 'DI YOGYAKARTA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 35, 'name' => 'JAWA TIMUR', 'description' => 'JAWA TIMUR','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 36, 'name' => 'BANTEN', 'description' => 'BANTEN','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 51, 'name' => 'BALI', 'description' => 'BALI','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 52, 'name' => 'NUSA TENGGARA BARAT', 'description' => 'NUSA TENGGARA BARAT','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 53, 'name' => 'NUSA TENGGARA TIMUR', 'description' => 'NUSA TENGGARA TIMUR','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 61, 'name' => 'KALIMANTAN BARAT', 'description' => 'KALIMANTAN BARAT','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 62, 'name' => 'KALIMANTAN TENGAH', 'description' => 'KALIMANTAN TENGAH','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 63, 'name' => 'KALIMANTAN SELATAN', 'description' => 'KALIMANTAN SELATAN','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 64, 'name' => 'KALIMANTAN TIMUR', 'description' => 'KALIMANTAN TIMUR','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 65, 'name' => 'KALIMANTAN UTARA', 'description' => 'KALIMANTAN UTARA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 71, 'name' => 'SULAWESI UTARA', 'description' => 'SULAWESI UTARA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 72, 'name' => 'SULAWESI TENGAH', 'description' => 'SULAWESI TENGAH','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 73, 'name' => 'SULAWESI SELATAN', 'description' => 'SULAWESI SELATAN','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 74, 'name' => 'SULAWESI TENGGARA', 'description' => 'SULAWESI TENGGARA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 75, 'name' => 'GORONTALO', 'description' => 'GORONTALO','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 76, 'name' => 'SULAWESI BARAT', 'description' => 'SULAWESI BARAT','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 81, 'name' => 'MALUKU', 'description' => 'MALUKU','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 82, 'name' => 'MALUKU UTARA', 'description' => 'MALUKU UTARA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 91, 'name' => 'PAPUA BARAT', 'description' => 'PAPUA BARAT','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
             ['id' => 94, 'name' => 'PAPUA', 'description' => 'PAPUA','country_id' => 1,  'created_by' => 'System', 'updated_by' => 'System'],
         ];

         DB::table('provinces')->insert($provinces);

        /**
         * ================== CITIES ===================
         */

         $cities = [
            ['id' => 1101, 'name' => 'KABUPATEN SIMEULUE', 'description' => 'KABUPATEN SIMEULUE','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1102, 'name' => 'KABUPATEN ACEH SINGKIL', 'description' => 'KABUPATEN ACEH SINGKIL','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1103, 'name' => 'KABUPATEN ACEH SELATAN', 'description' => 'KABUPATEN ACEH SELATAN','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1104, 'name' => 'KABUPATEN ACEH TENGGARA', 'description' => 'KABUPATEN ACEH TENGGARA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1105, 'name' => 'KABUPATEN ACEH TIMUR', 'description' => 'KABUPATEN ACEH TIMUR','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1106, 'name' => 'KABUPATEN ACEH TENGAH', 'description' => 'KABUPATEN ACEH TENGAH','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1107, 'name' => 'KABUPATEN ACEH BARAT', 'description' => 'KABUPATEN ACEH BARAT','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1108, 'name' => 'KABUPATEN ACEH BESAR', 'description' => 'KABUPATEN ACEH BESAR','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1109, 'name' => 'KABUPATEN PIDIE', 'description' => 'KABUPATEN PIDIE','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1110, 'name' => 'KABUPATEN BIREUEN', 'description' => 'KABUPATEN BIREUEN','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1111, 'name' => 'KABUPATEN ACEH UTARA', 'description' => 'KABUPATEN ACEH UTARA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1112, 'name' => 'KABUPATEN ACEH BARAT DAYA', 'description' => 'KABUPATEN ACEH BARAT DAYA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1113, 'name' => 'KABUPATEN GAYO LUES', 'description' => 'KABUPATEN GAYO LUES','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1114, 'name' => 'KABUPATEN ACEH TAMIANG', 'description' => 'KABUPATEN ACEH TAMIANG','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1115, 'name' => 'KABUPATEN NAGAN RAYA', 'description' => 'KABUPATEN NAGAN RAYA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1116, 'name' => 'KABUPATEN ACEH JAYA', 'description' => 'KABUPATEN ACEH JAYA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1117, 'name' => 'KABUPATEN BENER MERIAH', 'description' => 'KABUPATEN BENER MERIAH','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1118, 'name' => 'KABUPATEN PIDIE JAYA', 'description' => 'KABUPATEN PIDIE JAYA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1171, 'name' => 'KOTA BANDA ACEH', 'description' => 'KOTA BANDA ACEH','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1172, 'name' => 'KOTA SABANG', 'description' => 'KOTA SABANG','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1173, 'name' => 'KOTA LANGSA', 'description' => 'KOTA LANGSA','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1174, 'name' => 'KOTA LHOKSEUMAWE', 'description' => 'KOTA LHOKSEUMAWE','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1175, 'name' => 'KOTA SUBULUSSALAM', 'description' => 'KOTA SUBULUSSALAM','province_id' => 11,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1201, 'name' => 'KABUPATEN NIAS', 'description' => 'KABUPATEN NIAS','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1202, 'name' => 'KABUPATEN MANDAILING NATAL', 'description' => 'KABUPATEN MANDAILING NATAL','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1203, 'name' => 'KABUPATEN TAPANULI SELATAN', 'description' => 'KABUPATEN TAPANULI SELATAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1204, 'name' => 'KABUPATEN TAPANULI TENGAH', 'description' => 'KABUPATEN TAPANULI TENGAH','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1205, 'name' => 'KABUPATEN TAPANULI UTARA', 'description' => 'KABUPATEN TAPANULI UTARA','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1206, 'name' => 'KABUPATEN TOBA SAMOSIR', 'description' => 'KABUPATEN TOBA SAMOSIR','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1207, 'name' => 'KABUPATEN LABUHAN BATU', 'description' => 'KABUPATEN LABUHAN BATU','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1208, 'name' => 'KABUPATEN ASAHAN', 'description' => 'KABUPATEN ASAHAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1209, 'name' => 'KABUPATEN SIMALUNGUN', 'description' => 'KABUPATEN SIMALUNGUN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1210, 'name' => 'KABUPATEN DAIRI', 'description' => 'KABUPATEN DAIRI','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1211, 'name' => 'KABUPATEN KARO', 'description' => 'KABUPATEN KARO','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1212, 'name' => 'KABUPATEN DELI SERDANG', 'description' => 'KABUPATEN DELI SERDANG','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1213, 'name' => 'KABUPATEN LANGKAT', 'description' => 'KABUPATEN LANGKAT','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1214, 'name' => 'KABUPATEN NIAS SELATAN', 'description' => 'KABUPATEN NIAS SELATAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1215, 'name' => 'KABUPATEN HUMBANG HASUNDUTAN', 'description' => 'KABUPATEN HUMBANG HASUNDUTAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1216, 'name' => 'KABUPATEN PAKPAK BHARAT', 'description' => 'KABUPATEN PAKPAK BHARAT','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1217, 'name' => 'KABUPATEN SAMOSIR', 'description' => 'KABUPATEN SAMOSIR','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1218, 'name' => 'KABUPATEN SERDANG BEDAGAI', 'description' => 'KABUPATEN SERDANG BEDAGAI','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1219, 'name' => 'KABUPATEN BATU BARA', 'description' => 'KABUPATEN BATU BARA','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1220, 'name' => 'KABUPATEN PADANG LAWAS UTARA', 'description' => 'KABUPATEN PADANG LAWAS UTARA','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1221, 'name' => 'KABUPATEN PADANG LAWAS', 'description' => 'KABUPATEN PADANG LAWAS','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1222, 'name' => 'KABUPATEN LABUHAN BATU SELATAN', 'description' => 'KABUPATEN LABUHAN BATU SELATAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1223, 'name' => 'KABUPATEN LABUHAN BATU UTARA', 'description' => 'KABUPATEN LABUHAN BATU UTARA','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1224, 'name' => 'KABUPATEN NIAS UTARA', 'description' => 'KABUPATEN NIAS UTARA','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1225, 'name' => 'KABUPATEN NIAS BARAT', 'description' => 'KABUPATEN NIAS BARAT','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1271, 'name' => 'KOTA SIBOLGA', 'description' => 'KOTA SIBOLGA','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1272, 'name' => 'KOTA TANJUNG BALAI', 'description' => 'KOTA TANJUNG BALAI','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1273, 'name' => 'KOTA PEMATANG SIANTAR', 'description' => 'KOTA PEMATANG SIANTAR','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1274, 'name' => 'KOTA TEBING TINGGI', 'description' => 'KOTA TEBING TINGGI','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1275, 'name' => 'KOTA MEDAN', 'description' => 'KOTA MEDAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1276, 'name' => 'KOTA BINJAI', 'description' => 'KOTA BINJAI','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1277, 'name' => 'KOTA PADANGSIDIMPUAN', 'description' => 'KOTA PADANGSIDIMPUAN','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1278, 'name' => 'KOTA GUNUNGSITOLI', 'description' => 'KOTA GUNUNGSITOLI','province_id' => 12,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1301, 'name' => 'KABUPATEN KEPULAUAN MENTAWAI', 'description' => 'KABUPATEN KEPULAUAN MENTAWAI','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1302, 'name' => 'KABUPATEN PESISIR SELATAN', 'description' => 'KABUPATEN PESISIR SELATAN','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1303, 'name' => 'KABUPATEN SOLOK', 'description' => 'KABUPATEN SOLOK','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1304, 'name' => 'KABUPATEN SIJUNJUNG', 'description' => 'KABUPATEN SIJUNJUNG','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1305, 'name' => 'KABUPATEN TANAH DATAR', 'description' => 'KABUPATEN TANAH DATAR','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1306, 'name' => 'KABUPATEN PADANG PARIAMAN', 'description' => 'KABUPATEN PADANG PARIAMAN','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1307, 'name' => 'KABUPATEN AGAM', 'description' => 'KABUPATEN AGAM','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1308, 'name' => 'KABUPATEN LIMA PULUH KOTA', 'description' => 'KABUPATEN LIMA PULUH KOTA','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1309, 'name' => 'KABUPATEN PASAMAN', 'description' => 'KABUPATEN PASAMAN','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1310, 'name' => 'KABUPATEN SOLOK SELATAN', 'description' => 'KABUPATEN SOLOK SELATAN','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1311, 'name' => 'KABUPATEN DHARMASRAYA', 'description' => 'KABUPATEN DHARMASRAYA','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1312, 'name' => 'KABUPATEN PASAMAN BARAT', 'description' => 'KABUPATEN PASAMAN BARAT','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1371, 'name' => 'KOTA PADANG', 'description' => 'KOTA PADANG','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1372, 'name' => 'KOTA SOLOK', 'description' => 'KOTA SOLOK','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1373, 'name' => 'KOTA SAWAH LUNTO', 'description' => 'KOTA SAWAH LUNTO','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1374, 'name' => 'KOTA PADANG PANJANG', 'description' => 'KOTA PADANG PANJANG','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1375, 'name' => 'KOTA BUKITTINGGI', 'description' => 'KOTA BUKITTINGGI','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1376, 'name' => 'KOTA PAYAKUMBUH', 'description' => 'KOTA PAYAKUMBUH','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1377, 'name' => 'KOTA PARIAMAN', 'description' => 'KOTA PARIAMAN','province_id' => 13,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1401, 'name' => 'KABUPATEN KUANTAN SINGINGI', 'description' => 'KABUPATEN KUANTAN SINGINGI','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1402, 'name' => 'KABUPATEN INDRAGIRI HULU', 'description' => 'KABUPATEN INDRAGIRI HULU','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1403, 'name' => 'KABUPATEN INDRAGIRI HILIR', 'description' => 'KABUPATEN INDRAGIRI HILIR','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1404, 'name' => 'KABUPATEN PELALAWAN', 'description' => 'KABUPATEN PELALAWAN','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1405, 'name' => 'KABUPATEN S I A K', 'description' => 'KABUPATEN S I A K','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1406, 'name' => 'KABUPATEN KAMPAR', 'description' => 'KABUPATEN KAMPAR','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1407, 'name' => 'KABUPATEN ROKAN HULU', 'description' => 'KABUPATEN ROKAN HULU','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1408, 'name' => 'KABUPATEN BENGKALIS', 'description' => 'KABUPATEN BENGKALIS','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1409, 'name' => 'KABUPATEN ROKAN HILIR', 'description' => 'KABUPATEN ROKAN HILIR','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1410, 'name' => 'KABUPATEN KEPULAUAN MERANTI', 'description' => 'KABUPATEN KEPULAUAN MERANTI','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1471, 'name' => 'KOTA PEKANBARU', 'description' => 'KOTA PEKANBARU','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1473, 'name' => 'KOTA D U M A I', 'description' => 'KOTA D U M A I','province_id' => 14,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1501, 'name' => 'KABUPATEN KERINCI', 'description' => 'KABUPATEN KERINCI','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1502, 'name' => 'KABUPATEN MERANGIN', 'description' => 'KABUPATEN MERANGIN','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1503, 'name' => 'KABUPATEN SAROLANGUN', 'description' => 'KABUPATEN SAROLANGUN','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1504, 'name' => 'KABUPATEN BATANG HARI', 'description' => 'KABUPATEN BATANG HARI','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1505, 'name' => 'KABUPATEN MUARO JAMBI', 'description' => 'KABUPATEN MUARO JAMBI','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1506, 'name' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'description' => 'KABUPATEN TANJUNG JABUNG TIMUR','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1507, 'name' => 'KABUPATEN TANJUNG JABUNG BARAT', 'description' => 'KABUPATEN TANJUNG JABUNG BARAT','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1508, 'name' => 'KABUPATEN TEBO', 'description' => 'KABUPATEN TEBO','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1509, 'name' => 'KABUPATEN BUNGO', 'description' => 'KABUPATEN BUNGO','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1571, 'name' => 'KOTA JAMBI', 'description' => 'KOTA JAMBI','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1572, 'name' => 'KOTA SUNGAI PENUH', 'description' => 'KOTA SUNGAI PENUH','province_id' => 15,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1601, 'name' => 'KABUPATEN OGAN KOMERING ULU', 'description' => 'KABUPATEN OGAN KOMERING ULU','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1602, 'name' => 'KABUPATEN OGAN KOMERING ILIR', 'description' => 'KABUPATEN OGAN KOMERING ILIR','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1603, 'name' => 'KABUPATEN MUARA ENIM', 'description' => 'KABUPATEN MUARA ENIM','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1604, 'name' => 'KABUPATEN LAHAT', 'description' => 'KABUPATEN LAHAT','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1605, 'name' => 'KABUPATEN MUSI RAWAS', 'description' => 'KABUPATEN MUSI RAWAS','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1606, 'name' => 'KABUPATEN MUSI BANYUASIN', 'description' => 'KABUPATEN MUSI BANYUASIN','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1607, 'name' => 'KABUPATEN BANYU ASIN', 'description' => 'KABUPATEN BANYU ASIN','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1608, 'name' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'description' => 'KABUPATEN OGAN KOMERING ULU SELATAN','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1609, 'name' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'description' => 'KABUPATEN OGAN KOMERING ULU TIMUR','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1610, 'name' => 'KABUPATEN OGAN ILIR', 'description' => 'KABUPATEN OGAN ILIR','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1611, 'name' => 'KABUPATEN EMPAT LAWANG', 'description' => 'KABUPATEN EMPAT LAWANG','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1612, 'name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'description' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1613, 'name' => 'KABUPATEN MUSI RAWAS UTARA', 'description' => 'KABUPATEN MUSI RAWAS UTARA','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1671, 'name' => 'KOTA PALEMBANG', 'description' => 'KOTA PALEMBANG','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1672, 'name' => 'KOTA PRABUMULIH', 'description' => 'KOTA PRABUMULIH','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1673, 'name' => 'KOTA PAGAR ALAM', 'description' => 'KOTA PAGAR ALAM','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1674, 'name' => 'KOTA LUBUKLINGGAU', 'description' => 'KOTA LUBUKLINGGAU','province_id' => 16,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1701, 'name' => 'KABUPATEN BENGKULU SELATAN', 'description' => 'KABUPATEN BENGKULU SELATAN','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1702, 'name' => 'KABUPATEN REJANG LEBONG', 'description' => 'KABUPATEN REJANG LEBONG','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1703, 'name' => 'KABUPATEN BENGKULU UTARA', 'description' => 'KABUPATEN BENGKULU UTARA','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1704, 'name' => 'KABUPATEN KAUR', 'description' => 'KABUPATEN KAUR','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1705, 'name' => 'KABUPATEN SELUMA', 'description' => 'KABUPATEN SELUMA','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1706, 'name' => 'KABUPATEN MUKOMUKO', 'description' => 'KABUPATEN MUKOMUKO','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1707, 'name' => 'KABUPATEN LEBONG', 'description' => 'KABUPATEN LEBONG','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1708, 'name' => 'KABUPATEN KEPAHIANG', 'description' => 'KABUPATEN KEPAHIANG','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1709, 'name' => 'KABUPATEN BENGKULU TENGAH', 'description' => 'KABUPATEN BENGKULU TENGAH','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1771, 'name' => 'KOTA BENGKULU', 'description' => 'KOTA BENGKULU','province_id' => 17,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1801, 'name' => 'KABUPATEN LAMPUNG BARAT', 'description' => 'KABUPATEN LAMPUNG BARAT','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1802, 'name' => 'KABUPATEN TANGGAMUS', 'description' => 'KABUPATEN TANGGAMUS','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1803, 'name' => 'KABUPATEN LAMPUNG SELATAN', 'description' => 'KABUPATEN LAMPUNG SELATAN','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1804, 'name' => 'KABUPATEN LAMPUNG TIMUR', 'description' => 'KABUPATEN LAMPUNG TIMUR','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1805, 'name' => 'KABUPATEN LAMPUNG TENGAH', 'description' => 'KABUPATEN LAMPUNG TENGAH','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1806, 'name' => 'KABUPATEN LAMPUNG UTARA', 'description' => 'KABUPATEN LAMPUNG UTARA','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1807, 'name' => 'KABUPATEN WAY KANAN', 'description' => 'KABUPATEN WAY KANAN','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1808, 'name' => 'KABUPATEN TULANGBAWANG', 'description' => 'KABUPATEN TULANGBAWANG','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1809, 'name' => 'KABUPATEN PESAWARAN', 'description' => 'KABUPATEN PESAWARAN','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1810, 'name' => 'KABUPATEN PRINGSEWU', 'description' => 'KABUPATEN PRINGSEWU','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1811, 'name' => 'KABUPATEN MESUJI', 'description' => 'KABUPATEN MESUJI','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1812, 'name' => 'KABUPATEN TULANG BAWANG BARAT', 'description' => 'KABUPATEN TULANG BAWANG BARAT','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1813, 'name' => 'KABUPATEN PESISIR BARAT', 'description' => 'KABUPATEN PESISIR BARAT','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1871, 'name' => 'KOTA BANDAR LAMPUNG', 'description' => 'KOTA BANDAR LAMPUNG','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1872, 'name' => 'KOTA METRO', 'description' => 'KOTA METRO','province_id' => 18,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1901, 'name' => 'KABUPATEN BANGKA', 'description' => 'KABUPATEN BANGKA','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1902, 'name' => 'KABUPATEN BELITUNG', 'description' => 'KABUPATEN BELITUNG','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1903, 'name' => 'KABUPATEN BANGKA BARAT', 'description' => 'KABUPATEN BANGKA BARAT','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1904, 'name' => 'KABUPATEN BANGKA TENGAH', 'description' => 'KABUPATEN BANGKA TENGAH','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1905, 'name' => 'KABUPATEN BANGKA SELATAN', 'description' => 'KABUPATEN BANGKA SELATAN','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1906, 'name' => 'KABUPATEN BELITUNG TIMUR', 'description' => 'KABUPATEN BELITUNG TIMUR','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 1971, 'name' => 'KOTA PANGKAL PINANG', 'description' => 'KOTA PANGKAL PINANG','province_id' => 19,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2101, 'name' => 'KABUPATEN KARIMUN', 'description' => 'KABUPATEN KARIMUN','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2102, 'name' => 'KABUPATEN BINTAN', 'description' => 'KABUPATEN BINTAN','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2103, 'name' => 'KABUPATEN NATUNA', 'description' => 'KABUPATEN NATUNA','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2104, 'name' => 'KABUPATEN LINGGA', 'description' => 'KABUPATEN LINGGA','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2105, 'name' => 'KABUPATEN KEPULAUAN ANAMBAS', 'description' => 'KABUPATEN KEPULAUAN ANAMBAS','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2171, 'name' => 'KOTA B A T A M', 'description' => 'KOTA B A T A M','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 2172, 'name' => 'KOTA TANJUNG PINANG', 'description' => 'KOTA TANJUNG PINANG','province_id' => 21,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3101, 'name' => 'KABUPATEN KEPULAUAN SERIBU', 'description' => 'KABUPATEN KEPULAUAN SERIBU','province_id' => 31,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3171, 'name' => 'KOTA JAKARTA SELATAN', 'description' => 'KOTA JAKARTA SELATAN','province_id' => 31,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3172, 'name' => 'KOTA JAKARTA TIMUR', 'description' => 'KOTA JAKARTA TIMUR','province_id' => 31,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3173, 'name' => 'KOTA JAKARTA PUSAT', 'description' => 'KOTA JAKARTA PUSAT','province_id' => 31,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3174, 'name' => 'KOTA JAKARTA BARAT', 'description' => 'KOTA JAKARTA BARAT','province_id' => 31,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3175, 'name' => 'KOTA JAKARTA UTARA', 'description' => 'KOTA JAKARTA UTARA','province_id' => 31,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3201, 'name' => 'KABUPATEN BOGOR', 'description' => 'KABUPATEN BOGOR','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3202, 'name' => 'KABUPATEN SUKABUMI', 'description' => 'KABUPATEN SUKABUMI','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3203, 'name' => 'KABUPATEN CIANJUR', 'description' => 'KABUPATEN CIANJUR','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3204, 'name' => 'KABUPATEN BANDUNG', 'description' => 'KABUPATEN BANDUNG','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3205, 'name' => 'KABUPATEN GARUT', 'description' => 'KABUPATEN GARUT','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3206, 'name' => 'KABUPATEN TASIKMALAYA', 'description' => 'KABUPATEN TASIKMALAYA','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3207, 'name' => 'KABUPATEN CIAMIS', 'description' => 'KABUPATEN CIAMIS','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3208, 'name' => 'KABUPATEN KUNINGAN', 'description' => 'KABUPATEN KUNINGAN','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3209, 'name' => 'KABUPATEN CIREBON', 'description' => 'KABUPATEN CIREBON','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3210, 'name' => 'KABUPATEN MAJALENGKA', 'description' => 'KABUPATEN MAJALENGKA','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3211, 'name' => 'KABUPATEN SUMEDANG', 'description' => 'KABUPATEN SUMEDANG','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3212, 'name' => 'KABUPATEN INDRAMAYU', 'description' => 'KABUPATEN INDRAMAYU','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3213, 'name' => 'KABUPATEN SUBANG', 'description' => 'KABUPATEN SUBANG','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3214, 'name' => 'KABUPATEN PURWAKARTA', 'description' => 'KABUPATEN PURWAKARTA','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3215, 'name' => 'KABUPATEN KARAWANG', 'description' => 'KABUPATEN KARAWANG','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3216, 'name' => 'KABUPATEN BEKASI', 'description' => 'KABUPATEN BEKASI','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3217, 'name' => 'KABUPATEN BANDUNG BARAT', 'description' => 'KABUPATEN BANDUNG BARAT','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3218, 'name' => 'KABUPATEN PANGANDARAN', 'description' => 'KABUPATEN PANGANDARAN','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3271, 'name' => 'KOTA BOGOR', 'description' => 'KOTA BOGOR','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3272, 'name' => 'KOTA SUKABUMI', 'description' => 'KOTA SUKABUMI','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3273, 'name' => 'KOTA BANDUNG', 'description' => 'KOTA BANDUNG','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3274, 'name' => 'KOTA CIREBON', 'description' => 'KOTA CIREBON','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3275, 'name' => 'KOTA BEKASI', 'description' => 'KOTA BEKASI','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3276, 'name' => 'KOTA DEPOK', 'description' => 'KOTA DEPOK','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3277, 'name' => 'KOTA CIMAHI', 'description' => 'KOTA CIMAHI','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3278, 'name' => 'KOTA TASIKMALAYA', 'description' => 'KOTA TASIKMALAYA','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3279, 'name' => 'KOTA BANJAR', 'description' => 'KOTA BANJAR','province_id' => 32,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3301, 'name' => 'KABUPATEN CILACAP', 'description' => 'KABUPATEN CILACAP','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3302, 'name' => 'KABUPATEN BANYUMAS', 'description' => 'KABUPATEN BANYUMAS','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3303, 'name' => 'KABUPATEN PURBALINGGA', 'description' => 'KABUPATEN PURBALINGGA','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3304, 'name' => 'KABUPATEN BANJARNEGARA', 'description' => 'KABUPATEN BANJARNEGARA','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3305, 'name' => 'KABUPATEN KEBUMEN', 'description' => 'KABUPATEN KEBUMEN','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3306, 'name' => 'KABUPATEN PURWOREJO', 'description' => 'KABUPATEN PURWOREJO','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3307, 'name' => 'KABUPATEN WONOSOBO', 'description' => 'KABUPATEN WONOSOBO','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3308, 'name' => 'KABUPATEN MAGELANG', 'description' => 'KABUPATEN MAGELANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3309, 'name' => 'KABUPATEN BOYOLALI', 'description' => 'KABUPATEN BOYOLALI','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3310, 'name' => 'KABUPATEN KLATEN', 'description' => 'KABUPATEN KLATEN','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3311, 'name' => 'KABUPATEN SUKOHARJO', 'description' => 'KABUPATEN SUKOHARJO','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3312, 'name' => 'KABUPATEN WONOGIRI', 'description' => 'KABUPATEN WONOGIRI','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3313, 'name' => 'KABUPATEN KARANGANYAR', 'description' => 'KABUPATEN KARANGANYAR','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3314, 'name' => 'KABUPATEN SRAGEN', 'description' => 'KABUPATEN SRAGEN','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3315, 'name' => 'KABUPATEN GROBOGAN', 'description' => 'KABUPATEN GROBOGAN','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3316, 'name' => 'KABUPATEN BLORA', 'description' => 'KABUPATEN BLORA','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3317, 'name' => 'KABUPATEN REMBANG', 'description' => 'KABUPATEN REMBANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3318, 'name' => 'KABUPATEN PATI', 'description' => 'KABUPATEN PATI','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3319, 'name' => 'KABUPATEN KUDUS', 'description' => 'KABUPATEN KUDUS','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3320, 'name' => 'KABUPATEN JEPARA', 'description' => 'KABUPATEN JEPARA','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3321, 'name' => 'KABUPATEN DEMAK', 'description' => 'KABUPATEN DEMAK','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3322, 'name' => 'KABUPATEN SEMARANG', 'description' => 'KABUPATEN SEMARANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3323, 'name' => 'KABUPATEN TEMANGGUNG', 'description' => 'KABUPATEN TEMANGGUNG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3324, 'name' => 'KABUPATEN KENDAL', 'description' => 'KABUPATEN KENDAL','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3325, 'name' => 'KABUPATEN BATANG', 'description' => 'KABUPATEN BATANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3326, 'name' => 'KABUPATEN PEKALONGAN', 'description' => 'KABUPATEN PEKALONGAN','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3327, 'name' => 'KABUPATEN PEMALANG', 'description' => 'KABUPATEN PEMALANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3328, 'name' => 'KABUPATEN TEGAL', 'description' => 'KABUPATEN TEGAL','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3329, 'name' => 'KABUPATEN BREBES', 'description' => 'KABUPATEN BREBES','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3371, 'name' => 'KOTA MAGELANG', 'description' => 'KOTA MAGELANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3372, 'name' => 'KOTA SURAKARTA', 'description' => 'KOTA SURAKARTA','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3373, 'name' => 'KOTA SALATIGA', 'description' => 'KOTA SALATIGA','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3374, 'name' => 'KOTA SEMARANG', 'description' => 'KOTA SEMARANG','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3375, 'name' => 'KOTA PEKALONGAN', 'description' => 'KOTA PEKALONGAN','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3376, 'name' => 'KOTA TEGAL', 'description' => 'KOTA TEGAL','province_id' => 33,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3401, 'name' => 'KABUPATEN KULON PROGO', 'description' => 'KABUPATEN KULON PROGO','province_id' => 34,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3402, 'name' => 'KABUPATEN BANTUL', 'description' => 'KABUPATEN BANTUL','province_id' => 34,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3403, 'name' => 'KABUPATEN GUNUNG KIDUL', 'description' => 'KABUPATEN GUNUNG KIDUL','province_id' => 34,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3404, 'name' => 'KABUPATEN SLEMAN', 'description' => 'KABUPATEN SLEMAN','province_id' => 34,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3471, 'name' => 'KOTA YOGYAKARTA', 'description' => 'KOTA YOGYAKARTA','province_id' => 34,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3501, 'name' => 'KABUPATEN PACITAN', 'description' => 'KABUPATEN PACITAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3502, 'name' => 'KABUPATEN PONOROGO', 'description' => 'KABUPATEN PONOROGO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3503, 'name' => 'KABUPATEN TRENGGALEK', 'description' => 'KABUPATEN TRENGGALEK','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3504, 'name' => 'KABUPATEN TULUNGAGUNG', 'description' => 'KABUPATEN TULUNGAGUNG','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3505, 'name' => 'KABUPATEN BLITAR', 'description' => 'KABUPATEN BLITAR','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3506, 'name' => 'KABUPATEN KEDIRI', 'description' => 'KABUPATEN KEDIRI','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3507, 'name' => 'KABUPATEN MALANG', 'description' => 'KABUPATEN MALANG','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3508, 'name' => 'KABUPATEN LUMAJANG', 'description' => 'KABUPATEN LUMAJANG','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3509, 'name' => 'KABUPATEN JEMBER', 'description' => 'KABUPATEN JEMBER','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3510, 'name' => 'KABUPATEN BANYUWANGI', 'description' => 'KABUPATEN BANYUWANGI','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3511, 'name' => 'KABUPATEN BONDOWOSO', 'description' => 'KABUPATEN BONDOWOSO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3512, 'name' => 'KABUPATEN SITUBONDO', 'description' => 'KABUPATEN SITUBONDO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3513, 'name' => 'KABUPATEN PROBOLINGGO', 'description' => 'KABUPATEN PROBOLINGGO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3514, 'name' => 'KABUPATEN PASURUAN', 'description' => 'KABUPATEN PASURUAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3515, 'name' => 'KABUPATEN SIDOARJO', 'description' => 'KABUPATEN SIDOARJO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3516, 'name' => 'KABUPATEN MOJOKERTO', 'description' => 'KABUPATEN MOJOKERTO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3517, 'name' => 'KABUPATEN JOMBANG', 'description' => 'KABUPATEN JOMBANG','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3518, 'name' => 'KABUPATEN NGANJUK', 'description' => 'KABUPATEN NGANJUK','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3519, 'name' => 'KABUPATEN MADIUN', 'description' => 'KABUPATEN MADIUN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3520, 'name' => 'KABUPATEN MAGETAN', 'description' => 'KABUPATEN MAGETAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3521, 'name' => 'KABUPATEN NGAWI', 'description' => 'KABUPATEN NGAWI','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3522, 'name' => 'KABUPATEN BOJONEGORO', 'description' => 'KABUPATEN BOJONEGORO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3523, 'name' => 'KABUPATEN TUBAN', 'description' => 'KABUPATEN TUBAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3524, 'name' => 'KABUPATEN LAMONGAN', 'description' => 'KABUPATEN LAMONGAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3525, 'name' => 'KABUPATEN GRESIK', 'description' => 'KABUPATEN GRESIK','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3526, 'name' => 'KABUPATEN BANGKALAN', 'description' => 'KABUPATEN BANGKALAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3527, 'name' => 'KABUPATEN SAMPANG', 'description' => 'KABUPATEN SAMPANG','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3528, 'name' => 'KABUPATEN PAMEKASAN', 'description' => 'KABUPATEN PAMEKASAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3529, 'name' => 'KABUPATEN SUMENEP', 'description' => 'KABUPATEN SUMENEP','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3571, 'name' => 'KOTA KEDIRI', 'description' => 'KOTA KEDIRI','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3572, 'name' => 'KOTA BLITAR', 'description' => 'KOTA BLITAR','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3573, 'name' => 'KOTA MALANG', 'description' => 'KOTA MALANG','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3574, 'name' => 'KOTA PROBOLINGGO', 'description' => 'KOTA PROBOLINGGO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3575, 'name' => 'KOTA PASURUAN', 'description' => 'KOTA PASURUAN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3576, 'name' => 'KOTA MOJOKERTO', 'description' => 'KOTA MOJOKERTO','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3577, 'name' => 'KOTA MADIUN', 'description' => 'KOTA MADIUN','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3578, 'name' => 'KOTA SURABAYA', 'description' => 'KOTA SURABAYA','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3579, 'name' => 'KOTA BATU', 'description' => 'KOTA BATU','province_id' => 35,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3601, 'name' => 'KABUPATEN PANDEGLANG', 'description' => 'KABUPATEN PANDEGLANG','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3602, 'name' => 'KABUPATEN LEBAK', 'description' => 'KABUPATEN LEBAK','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3603, 'name' => 'KABUPATEN TANGERANG', 'description' => 'KABUPATEN TANGERANG','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3604, 'name' => 'KABUPATEN SERANG', 'description' => 'KABUPATEN SERANG','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3671, 'name' => 'KOTA TANGERANG', 'description' => 'KOTA TANGERANG','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3672, 'name' => 'KOTA CILEGON', 'description' => 'KOTA CILEGON','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3673, 'name' => 'KOTA SERANG', 'description' => 'KOTA SERANG','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 3674, 'name' => 'KOTA TANGERANG SELATAN', 'description' => 'KOTA TANGERANG SELATAN','province_id' => 36,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5101, 'name' => 'KABUPATEN JEMBRANA', 'description' => 'KABUPATEN JEMBRANA','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5102, 'name' => 'KABUPATEN TABANAN', 'description' => 'KABUPATEN TABANAN','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5103, 'name' => 'KABUPATEN BADUNG', 'description' => 'KABUPATEN BADUNG','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5104, 'name' => 'KABUPATEN GIANYAR', 'description' => 'KABUPATEN GIANYAR','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5105, 'name' => 'KABUPATEN KLUNGKUNG', 'description' => 'KABUPATEN KLUNGKUNG','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5106, 'name' => 'KABUPATEN BANGLI', 'description' => 'KABUPATEN BANGLI','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5107, 'name' => 'KABUPATEN KARANG ASEM', 'description' => 'KABUPATEN KARANG ASEM','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5108, 'name' => 'KABUPATEN BULELENG', 'description' => 'KABUPATEN BULELENG','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5171, 'name' => 'KOTA DENPASAR', 'description' => 'KOTA DENPASAR','province_id' => 51,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5201, 'name' => 'KABUPATEN LOMBOK BARAT', 'description' => 'KABUPATEN LOMBOK BARAT','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5202, 'name' => 'KABUPATEN LOMBOK TENGAH', 'description' => 'KABUPATEN LOMBOK TENGAH','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5203, 'name' => 'KABUPATEN LOMBOK TIMUR', 'description' => 'KABUPATEN LOMBOK TIMUR','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5204, 'name' => 'KABUPATEN SUMBAWA', 'description' => 'KABUPATEN SUMBAWA','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5205, 'name' => 'KABUPATEN DOMPU', 'description' => 'KABUPATEN DOMPU','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5206, 'name' => 'KABUPATEN BIMA', 'description' => 'KABUPATEN BIMA','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5207, 'name' => 'KABUPATEN SUMBAWA BARAT', 'description' => 'KABUPATEN SUMBAWA BARAT','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5208, 'name' => 'KABUPATEN LOMBOK UTARA', 'description' => 'KABUPATEN LOMBOK UTARA','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5271, 'name' => 'KOTA MATARAM', 'description' => 'KOTA MATARAM','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5272, 'name' => 'KOTA BIMA', 'description' => 'KOTA BIMA','province_id' => 52,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5301, 'name' => 'KABUPATEN SUMBA BARAT', 'description' => 'KABUPATEN SUMBA BARAT','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5302, 'name' => 'KABUPATEN SUMBA TIMUR', 'description' => 'KABUPATEN SUMBA TIMUR','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5303, 'name' => 'KABUPATEN KUPANG', 'description' => 'KABUPATEN KUPANG','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5304, 'name' => 'KABUPATEN TIMOR TENGAH SELATAN', 'description' => 'KABUPATEN TIMOR TENGAH SELATAN','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5305, 'name' => 'KABUPATEN TIMOR TENGAH UTARA', 'description' => 'KABUPATEN TIMOR TENGAH UTARA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5306, 'name' => 'KABUPATEN BELU', 'description' => 'KABUPATEN BELU','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5307, 'name' => 'KABUPATEN ALOR', 'description' => 'KABUPATEN ALOR','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5308, 'name' => 'KABUPATEN LEMBATA', 'description' => 'KABUPATEN LEMBATA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5309, 'name' => 'KABUPATEN FLORES TIMUR', 'description' => 'KABUPATEN FLORES TIMUR','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5310, 'name' => 'KABUPATEN SIKKA', 'description' => 'KABUPATEN SIKKA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5311, 'name' => 'KABUPATEN ENDE', 'description' => 'KABUPATEN ENDE','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5312, 'name' => 'KABUPATEN NGADA', 'description' => 'KABUPATEN NGADA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5313, 'name' => 'KABUPATEN MANGGARAI', 'description' => 'KABUPATEN MANGGARAI','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5314, 'name' => 'KABUPATEN ROTE NDAO', 'description' => 'KABUPATEN ROTE NDAO','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5315, 'name' => 'KABUPATEN MANGGARAI BARAT', 'description' => 'KABUPATEN MANGGARAI BARAT','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5316, 'name' => 'KABUPATEN SUMBA TENGAH', 'description' => 'KABUPATEN SUMBA TENGAH','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5317, 'name' => 'KABUPATEN SUMBA BARAT DAYA', 'description' => 'KABUPATEN SUMBA BARAT DAYA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5318, 'name' => 'KABUPATEN NAGEKEO', 'description' => 'KABUPATEN NAGEKEO','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5319, 'name' => 'KABUPATEN MANGGARAI TIMUR', 'description' => 'KABUPATEN MANGGARAI TIMUR','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5320, 'name' => 'KABUPATEN SABU RAIJUA', 'description' => 'KABUPATEN SABU RAIJUA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5321, 'name' => 'KABUPATEN MALAKA', 'description' => 'KABUPATEN MALAKA','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 5371, 'name' => 'KOTA KUPANG', 'description' => 'KOTA KUPANG','province_id' => 53,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6101, 'name' => 'KABUPATEN SAMBAS', 'description' => 'KABUPATEN SAMBAS','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6102, 'name' => 'KABUPATEN BENGKAYANG', 'description' => 'KABUPATEN BENGKAYANG','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6103, 'name' => 'KABUPATEN LANDAK', 'description' => 'KABUPATEN LANDAK','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6104, 'name' => 'KABUPATEN MEMPAWAH', 'description' => 'KABUPATEN MEMPAWAH','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6105, 'name' => 'KABUPATEN SANGGAU', 'description' => 'KABUPATEN SANGGAU','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6106, 'name' => 'KABUPATEN KETAPANG', 'description' => 'KABUPATEN KETAPANG','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6107, 'name' => 'KABUPATEN SINTANG', 'description' => 'KABUPATEN SINTANG','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6108, 'name' => 'KABUPATEN KAPUAS HULU', 'description' => 'KABUPATEN KAPUAS HULU','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6109, 'name' => 'KABUPATEN SEKADAU', 'description' => 'KABUPATEN SEKADAU','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6110, 'name' => 'KABUPATEN MELAWI', 'description' => 'KABUPATEN MELAWI','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6111, 'name' => 'KABUPATEN KAYONG UTARA', 'description' => 'KABUPATEN KAYONG UTARA','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6112, 'name' => 'KABUPATEN KUBU RAYA', 'description' => 'KABUPATEN KUBU RAYA','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6171, 'name' => 'KOTA PONTIANAK', 'description' => 'KOTA PONTIANAK','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6172, 'name' => 'KOTA SINGKAWANG', 'description' => 'KOTA SINGKAWANG','province_id' => 61,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6201, 'name' => 'KABUPATEN KOTAWARINGIN BARAT', 'description' => 'KABUPATEN KOTAWARINGIN BARAT','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6202, 'name' => 'KABUPATEN KOTAWARINGIN TIMUR', 'description' => 'KABUPATEN KOTAWARINGIN TIMUR','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6203, 'name' => 'KABUPATEN KAPUAS', 'description' => 'KABUPATEN KAPUAS','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6204, 'name' => 'KABUPATEN BARITO SELATAN', 'description' => 'KABUPATEN BARITO SELATAN','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6205, 'name' => 'KABUPATEN BARITO UTARA', 'description' => 'KABUPATEN BARITO UTARA','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6206, 'name' => 'KABUPATEN SUKAMARA', 'description' => 'KABUPATEN SUKAMARA','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6207, 'name' => 'KABUPATEN LAMANDAU', 'description' => 'KABUPATEN LAMANDAU','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6208, 'name' => 'KABUPATEN SERUYAN', 'description' => 'KABUPATEN SERUYAN','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6209, 'name' => 'KABUPATEN KATINGAN', 'description' => 'KABUPATEN KATINGAN','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6210, 'name' => 'KABUPATEN PULANG PISAU', 'description' => 'KABUPATEN PULANG PISAU','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6211, 'name' => 'KABUPATEN GUNUNG MAS', 'description' => 'KABUPATEN GUNUNG MAS','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6212, 'name' => 'KABUPATEN BARITO TIMUR', 'description' => 'KABUPATEN BARITO TIMUR','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6213, 'name' => 'KABUPATEN MURUNG RAYA', 'description' => 'KABUPATEN MURUNG RAYA','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6271, 'name' => 'KOTA PALANGKA RAYA', 'description' => 'KOTA PALANGKA RAYA','province_id' => 62,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6301, 'name' => 'KABUPATEN TANAH LAUT', 'description' => 'KABUPATEN TANAH LAUT','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6302, 'name' => 'KABUPATEN KOTA BARU', 'description' => 'KABUPATEN KOTA BARU','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6303, 'name' => 'KABUPATEN BANJAR', 'description' => 'KABUPATEN BANJAR','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6304, 'name' => 'KABUPATEN BARITO KUALA', 'description' => 'KABUPATEN BARITO KUALA','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6305, 'name' => 'KABUPATEN TAPIN', 'description' => 'KABUPATEN TAPIN','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6306, 'name' => 'KABUPATEN HULU SUNGAI SELATAN', 'description' => 'KABUPATEN HULU SUNGAI SELATAN','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6307, 'name' => 'KABUPATEN HULU SUNGAI TENGAH', 'description' => 'KABUPATEN HULU SUNGAI TENGAH','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6308, 'name' => 'KABUPATEN HULU SUNGAI UTARA', 'description' => 'KABUPATEN HULU SUNGAI UTARA','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6309, 'name' => 'KABUPATEN TABALONG', 'description' => 'KABUPATEN TABALONG','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6310, 'name' => 'KABUPATEN TANAH BUMBU', 'description' => 'KABUPATEN TANAH BUMBU','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6311, 'name' => 'KABUPATEN BALANGAN', 'description' => 'KABUPATEN BALANGAN','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6371, 'name' => 'KOTA BANJARMASIN', 'description' => 'KOTA BANJARMASIN','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6372, 'name' => 'KOTA BANJAR BARU', 'description' => 'KOTA BANJAR BARU','province_id' => 63,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6401, 'name' => 'KABUPATEN PASER', 'description' => 'KABUPATEN PASER','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6402, 'name' => 'KABUPATEN KUTAI BARAT', 'description' => 'KABUPATEN KUTAI BARAT','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6403, 'name' => 'KABUPATEN KUTAI KARTANEGARA', 'description' => 'KABUPATEN KUTAI KARTANEGARA','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6404, 'name' => 'KABUPATEN KUTAI TIMUR', 'description' => 'KABUPATEN KUTAI TIMUR','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6405, 'name' => 'KABUPATEN BERAU', 'description' => 'KABUPATEN BERAU','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6409, 'name' => 'KABUPATEN PENAJAM PASER UTARA', 'description' => 'KABUPATEN PENAJAM PASER UTARA','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6411, 'name' => 'KABUPATEN MAHAKAM HULU', 'description' => 'KABUPATEN MAHAKAM HULU','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6471, 'name' => 'KOTA BALIKPAPAN', 'description' => 'KOTA BALIKPAPAN','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6472, 'name' => 'KOTA SAMARINDA', 'description' => 'KOTA SAMARINDA','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6474, 'name' => 'KOTA BONTANG', 'description' => 'KOTA BONTANG','province_id' => 64,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6501, 'name' => 'KABUPATEN MALINAU', 'description' => 'KABUPATEN MALINAU','province_id' => 65,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6502, 'name' => 'KABUPATEN BULUNGAN', 'description' => 'KABUPATEN BULUNGAN','province_id' => 65,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6503, 'name' => 'KABUPATEN TANA TIDUNG', 'description' => 'KABUPATEN TANA TIDUNG','province_id' => 65,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6504, 'name' => 'KABUPATEN NUNUKAN', 'description' => 'KABUPATEN NUNUKAN','province_id' => 65,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 6571, 'name' => 'KOTA TARAKAN', 'description' => 'KOTA TARAKAN','province_id' => 65,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7101, 'name' => 'KABUPATEN BOLAANG MONGONDOW', 'description' => 'KABUPATEN BOLAANG MONGONDOW','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7102, 'name' => 'KABUPATEN MINAHASA', 'description' => 'KABUPATEN MINAHASA','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7103, 'name' => 'KABUPATEN KEPULAUAN SANGIHE', 'description' => 'KABUPATEN KEPULAUAN SANGIHE','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7104, 'name' => 'KABUPATEN KEPULAUAN TALAUD', 'description' => 'KABUPATEN KEPULAUAN TALAUD','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7105, 'name' => 'KABUPATEN MINAHASA SELATAN', 'description' => 'KABUPATEN MINAHASA SELATAN','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7106, 'name' => 'KABUPATEN MINAHASA UTARA', 'description' => 'KABUPATEN MINAHASA UTARA','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7107, 'name' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'description' => 'KABUPATEN BOLAANG MONGONDOW UTARA','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7108, 'name' => 'KABUPATEN SIAU TAGULANDANG BIARO', 'description' => 'KABUPATEN SIAU TAGULANDANG BIARO','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7109, 'name' => 'KABUPATEN MINAHASA TENGGARA', 'description' => 'KABUPATEN MINAHASA TENGGARA','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7110, 'name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'description' => 'KABUPATEN BOLAANG MONGONDOW SELATAN','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7111, 'name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'description' => 'KABUPATEN BOLAANG MONGONDOW TIMUR','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7171, 'name' => 'KOTA MANADO', 'description' => 'KOTA MANADO','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7172, 'name' => 'KOTA BITUNG', 'description' => 'KOTA BITUNG','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7173, 'name' => 'KOTA TOMOHON', 'description' => 'KOTA TOMOHON','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7174, 'name' => 'KOTA KOTAMOBAGU', 'description' => 'KOTA KOTAMOBAGU','province_id' => 71,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7201, 'name' => 'KABUPATEN BANGGAI KEPULAUAN', 'description' => 'KABUPATEN BANGGAI KEPULAUAN','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7202, 'name' => 'KABUPATEN BANGGAI', 'description' => 'KABUPATEN BANGGAI','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7203, 'name' => 'KABUPATEN MOROWALI', 'description' => 'KABUPATEN MOROWALI','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7204, 'name' => 'KABUPATEN POSO', 'description' => 'KABUPATEN POSO','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7205, 'name' => 'KABUPATEN DONGGALA', 'description' => 'KABUPATEN DONGGALA','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7206, 'name' => 'KABUPATEN TOLI-TOLI', 'description' => 'KABUPATEN TOLI-TOLI','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7207, 'name' => 'KABUPATEN BUOL', 'description' => 'KABUPATEN BUOL','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7208, 'name' => 'KABUPATEN PARIGI MOUTONG', 'description' => 'KABUPATEN PARIGI MOUTONG','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7209, 'name' => 'KABUPATEN TOJO UNA-UNA', 'description' => 'KABUPATEN TOJO UNA-UNA','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7210, 'name' => 'KABUPATEN SIGI', 'description' => 'KABUPATEN SIGI','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7211, 'name' => 'KABUPATEN BANGGAI LAUT', 'description' => 'KABUPATEN BANGGAI LAUT','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7212, 'name' => 'KABUPATEN MOROWALI UTARA', 'description' => 'KABUPATEN MOROWALI UTARA','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7271, 'name' => 'KOTA PALU', 'description' => 'KOTA PALU','province_id' => 72,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7301, 'name' => 'KABUPATEN KEPULAUAN SELAYAR', 'description' => 'KABUPATEN KEPULAUAN SELAYAR','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7302, 'name' => 'KABUPATEN BULUKUMBA', 'description' => 'KABUPATEN BULUKUMBA','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7303, 'name' => 'KABUPATEN BANTAENG', 'description' => 'KABUPATEN BANTAENG','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7304, 'name' => 'KABUPATEN JENEPONTO', 'description' => 'KABUPATEN JENEPONTO','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7305, 'name' => 'KABUPATEN TAKALAR', 'description' => 'KABUPATEN TAKALAR','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7306, 'name' => 'KABUPATEN GOWA', 'description' => 'KABUPATEN GOWA','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7307, 'name' => 'KABUPATEN SINJAI', 'description' => 'KABUPATEN SINJAI','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7308, 'name' => 'KABUPATEN MAROS', 'description' => 'KABUPATEN MAROS','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7309, 'name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'description' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7310, 'name' => 'KABUPATEN BARRU', 'description' => 'KABUPATEN BARRU','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7311, 'name' => 'KABUPATEN BONE', 'description' => 'KABUPATEN BONE','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7312, 'name' => 'KABUPATEN SOPPENG', 'description' => 'KABUPATEN SOPPENG','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7313, 'name' => 'KABUPATEN WAJO', 'description' => 'KABUPATEN WAJO','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7314, 'name' => 'KABUPATEN SIDENRENG RAPPANG', 'description' => 'KABUPATEN SIDENRENG RAPPANG','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7315, 'name' => 'KABUPATEN PINRANG', 'description' => 'KABUPATEN PINRANG','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7316, 'name' => 'KABUPATEN ENREKANG', 'description' => 'KABUPATEN ENREKANG','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7317, 'name' => 'KABUPATEN LUWU', 'description' => 'KABUPATEN LUWU','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7318, 'name' => 'KABUPATEN TANA TORAJA', 'description' => 'KABUPATEN TANA TORAJA','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7322, 'name' => 'KABUPATEN LUWU UTARA', 'description' => 'KABUPATEN LUWU UTARA','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7325, 'name' => 'KABUPATEN LUWU TIMUR', 'description' => 'KABUPATEN LUWU TIMUR','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7326, 'name' => 'KABUPATEN TORAJA UTARA', 'description' => 'KABUPATEN TORAJA UTARA','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7371, 'name' => 'KOTA MAKASSAR', 'description' => 'KOTA MAKASSAR','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7372, 'name' => 'KOTA PAREPARE', 'description' => 'KOTA PAREPARE','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7373, 'name' => 'KOTA PALOPO', 'description' => 'KOTA PALOPO','province_id' => 73,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7401, 'name' => 'KABUPATEN BUTON', 'description' => 'KABUPATEN BUTON','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7402, 'name' => 'KABUPATEN MUNA', 'description' => 'KABUPATEN MUNA','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7403, 'name' => 'KABUPATEN KONAWE', 'description' => 'KABUPATEN KONAWE','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7404, 'name' => 'KABUPATEN KOLAKA', 'description' => 'KABUPATEN KOLAKA','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7405, 'name' => 'KABUPATEN KONAWE SELATAN', 'description' => 'KABUPATEN KONAWE SELATAN','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7406, 'name' => 'KABUPATEN BOMBANA', 'description' => 'KABUPATEN BOMBANA','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7407, 'name' => 'KABUPATEN WAKATOBI', 'description' => 'KABUPATEN WAKATOBI','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7408, 'name' => 'KABUPATEN KOLAKA UTARA', 'description' => 'KABUPATEN KOLAKA UTARA','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7409, 'name' => 'KABUPATEN BUTON UTARA', 'description' => 'KABUPATEN BUTON UTARA','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7410, 'name' => 'KABUPATEN KONAWE UTARA', 'description' => 'KABUPATEN KONAWE UTARA','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7411, 'name' => 'KABUPATEN KOLAKA TIMUR', 'description' => 'KABUPATEN KOLAKA TIMUR','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7412, 'name' => 'KABUPATEN KONAWE KEPULAUAN', 'description' => 'KABUPATEN KONAWE KEPULAUAN','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7413, 'name' => 'KABUPATEN MUNA BARAT', 'description' => 'KABUPATEN MUNA BARAT','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7414, 'name' => 'KABUPATEN BUTON TENGAH', 'description' => 'KABUPATEN BUTON TENGAH','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7415, 'name' => 'KABUPATEN BUTON SELATAN', 'description' => 'KABUPATEN BUTON SELATAN','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7471, 'name' => 'KOTA KENDARI', 'description' => 'KOTA KENDARI','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7472, 'name' => 'KOTA BAUBAU', 'description' => 'KOTA BAUBAU','province_id' => 74,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7501, 'name' => 'KABUPATEN BOALEMO', 'description' => 'KABUPATEN BOALEMO','province_id' => 75,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7502, 'name' => 'KABUPATEN GORONTALO', 'description' => 'KABUPATEN GORONTALO','province_id' => 75,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7503, 'name' => 'KABUPATEN POHUWATO', 'description' => 'KABUPATEN POHUWATO','province_id' => 75,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7504, 'name' => 'KABUPATEN BONE BOLANGO', 'description' => 'KABUPATEN BONE BOLANGO','province_id' => 75,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7505, 'name' => 'KABUPATEN GORONTALO UTARA', 'description' => 'KABUPATEN GORONTALO UTARA','province_id' => 75,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7571, 'name' => 'KOTA GORONTALO', 'description' => 'KOTA GORONTALO','province_id' => 75,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7601, 'name' => 'KABUPATEN MAJENE', 'description' => 'KABUPATEN MAJENE','province_id' => 76,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7602, 'name' => 'KABUPATEN POLEWALI MANDAR', 'description' => 'KABUPATEN POLEWALI MANDAR','province_id' => 76,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7603, 'name' => 'KABUPATEN MAMASA', 'description' => 'KABUPATEN MAMASA','province_id' => 76,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7604, 'name' => 'KABUPATEN MAMUJU', 'description' => 'KABUPATEN MAMUJU','province_id' => 76,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7605, 'name' => 'KABUPATEN MAMUJU UTARA', 'description' => 'KABUPATEN MAMUJU UTARA','province_id' => 76,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 7606, 'name' => 'KABUPATEN MAMUJU TENGAH', 'description' => 'KABUPATEN MAMUJU TENGAH','province_id' => 76,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8101, 'name' => 'KABUPATEN MALUKU TENGGARA BARAT', 'description' => 'KABUPATEN MALUKU TENGGARA BARAT','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8102, 'name' => 'KABUPATEN MALUKU TENGGARA', 'description' => 'KABUPATEN MALUKU TENGGARA','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8103, 'name' => 'KABUPATEN MALUKU TENGAH', 'description' => 'KABUPATEN MALUKU TENGAH','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8104, 'name' => 'KABUPATEN BURU', 'description' => 'KABUPATEN BURU','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8105, 'name' => 'KABUPATEN KEPULAUAN ARU', 'description' => 'KABUPATEN KEPULAUAN ARU','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8106, 'name' => 'KABUPATEN SERAM BAGIAN BARAT', 'description' => 'KABUPATEN SERAM BAGIAN BARAT','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8107, 'name' => 'KABUPATEN SERAM BAGIAN TIMUR', 'description' => 'KABUPATEN SERAM BAGIAN TIMUR','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8108, 'name' => 'KABUPATEN MALUKU BARAT DAYA', 'description' => 'KABUPATEN MALUKU BARAT DAYA','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8109, 'name' => 'KABUPATEN BURU SELATAN', 'description' => 'KABUPATEN BURU SELATAN','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8171, 'name' => 'KOTA AMBON', 'description' => 'KOTA AMBON','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8172, 'name' => 'KOTA TUAL', 'description' => 'KOTA TUAL','province_id' => 81,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8201, 'name' => 'KABUPATEN HALMAHERA BARAT', 'description' => 'KABUPATEN HALMAHERA BARAT','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8202, 'name' => 'KABUPATEN HALMAHERA TENGAH', 'description' => 'KABUPATEN HALMAHERA TENGAH','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8203, 'name' => 'KABUPATEN KEPULAUAN SULA', 'description' => 'KABUPATEN KEPULAUAN SULA','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8204, 'name' => 'KABUPATEN HALMAHERA SELATAN', 'description' => 'KABUPATEN HALMAHERA SELATAN','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8205, 'name' => 'KABUPATEN HALMAHERA UTARA', 'description' => 'KABUPATEN HALMAHERA UTARA','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8206, 'name' => 'KABUPATEN HALMAHERA TIMUR', 'description' => 'KABUPATEN HALMAHERA TIMUR','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8207, 'name' => 'KABUPATEN PULAU MOROTAI', 'description' => 'KABUPATEN PULAU MOROTAI','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8208, 'name' => 'KABUPATEN PULAU TALIABU', 'description' => 'KABUPATEN PULAU TALIABU','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8271, 'name' => 'KOTA TERNATE', 'description' => 'KOTA TERNATE','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 8272, 'name' => 'KOTA TIDORE KEPULAUAN', 'description' => 'KOTA TIDORE KEPULAUAN','province_id' => 82,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9101, 'name' => 'KABUPATEN FAKFAK', 'description' => 'KABUPATEN FAKFAK','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9102, 'name' => 'KABUPATEN KAIMANA', 'description' => 'KABUPATEN KAIMANA','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9103, 'name' => 'KABUPATEN TELUK WONDAMA', 'description' => 'KABUPATEN TELUK WONDAMA','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9104, 'name' => 'KABUPATEN TELUK BINTUNI', 'description' => 'KABUPATEN TELUK BINTUNI','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9105, 'name' => 'KABUPATEN MANOKWARI', 'description' => 'KABUPATEN MANOKWARI','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9106, 'name' => 'KABUPATEN SORONG SELATAN', 'description' => 'KABUPATEN SORONG SELATAN','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9107, 'name' => 'KABUPATEN SORONG', 'description' => 'KABUPATEN SORONG','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9108, 'name' => 'KABUPATEN RAJA AMPAT', 'description' => 'KABUPATEN RAJA AMPAT','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9109, 'name' => 'KABUPATEN TAMBRAUW', 'description' => 'KABUPATEN TAMBRAUW','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9110, 'name' => 'KABUPATEN MAYBRAT', 'description' => 'KABUPATEN MAYBRAT','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9111, 'name' => 'KABUPATEN MANOKWARI SELATAN', 'description' => 'KABUPATEN MANOKWARI SELATAN','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9112, 'name' => 'KABUPATEN PEGUNUNGAN ARFAK', 'description' => 'KABUPATEN PEGUNUNGAN ARFAK','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9171, 'name' => 'KOTA SORONG', 'description' => 'KOTA SORONG','province_id' => 91,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9401, 'name' => 'KABUPATEN MERAUKE', 'description' => 'KABUPATEN MERAUKE','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9402, 'name' => 'KABUPATEN JAYAWIJAYA', 'description' => 'KABUPATEN JAYAWIJAYA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9403, 'name' => 'KABUPATEN JAYAPURA', 'description' => 'KABUPATEN JAYAPURA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9404, 'name' => 'KABUPATEN NABIRE', 'description' => 'KABUPATEN NABIRE','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9408, 'name' => 'KABUPATEN KEPULAUAN YAPEN', 'description' => 'KABUPATEN KEPULAUAN YAPEN','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9409, 'name' => 'KABUPATEN BIAK NUMFOR', 'description' => 'KABUPATEN BIAK NUMFOR','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9410, 'name' => 'KABUPATEN PANIAI', 'description' => 'KABUPATEN PANIAI','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9411, 'name' => 'KABUPATEN PUNCAK JAYA', 'description' => 'KABUPATEN PUNCAK JAYA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9412, 'name' => 'KABUPATEN MIMIKA', 'description' => 'KABUPATEN MIMIKA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9413, 'name' => 'KABUPATEN BOVEN DIGOEL', 'description' => 'KABUPATEN BOVEN DIGOEL','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9414, 'name' => 'KABUPATEN MAPPI', 'description' => 'KABUPATEN MAPPI','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9415, 'name' => 'KABUPATEN ASMAT', 'description' => 'KABUPATEN ASMAT','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9416, 'name' => 'KABUPATEN YAHUKIMO', 'description' => 'KABUPATEN YAHUKIMO','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9417, 'name' => 'KABUPATEN PEGUNUNGAN BINTANG', 'description' => 'KABUPATEN PEGUNUNGAN BINTANG','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9418, 'name' => 'KABUPATEN TOLIKARA', 'description' => 'KABUPATEN TOLIKARA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9419, 'name' => 'KABUPATEN SARMI', 'description' => 'KABUPATEN SARMI','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9420, 'name' => 'KABUPATEN KEEROM', 'description' => 'KABUPATEN KEEROM','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9426, 'name' => 'KABUPATEN WAROPEN', 'description' => 'KABUPATEN WAROPEN','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9427, 'name' => 'KABUPATEN SUPIORI', 'description' => 'KABUPATEN SUPIORI','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9428, 'name' => 'KABUPATEN MAMBERAMO RAYA', 'description' => 'KABUPATEN MAMBERAMO RAYA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9429, 'name' => 'KABUPATEN NDUGA', 'description' => 'KABUPATEN NDUGA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9430, 'name' => 'KABUPATEN LANNY JAYA', 'description' => 'KABUPATEN LANNY JAYA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9431, 'name' => 'KABUPATEN MAMBERAMO TENGAH', 'description' => 'KABUPATEN MAMBERAMO TENGAH','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9432, 'name' => 'KABUPATEN YALIMO', 'description' => 'KABUPATEN YALIMO','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9433, 'name' => 'KABUPATEN PUNCAK', 'description' => 'KABUPATEN PUNCAK','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9434, 'name' => 'KABUPATEN DOGIYAI', 'description' => 'KABUPATEN DOGIYAI','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9435, 'name' => 'KABUPATEN INTAN JAYA', 'description' => 'KABUPATEN INTAN JAYA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9436, 'name' => 'KABUPATEN DEIYAI', 'description' => 'KABUPATEN DEIYAI','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
            ['id' => 9471, 'name' => 'KOTA JAYAPURA', 'description' => 'KOTA JAYAPURA','province_id' => 94,  'created_by' => 'System', 'updated_by' => 'System'],
         ];

         DB::table('cities')->insert($cities);
    }
}
